#!/bin/bash
# Fatura AI — First Run Setup
# This script collects dev server credentials and saves them to .env
# Run once: bash setup.sh

ENV_FILE="$(dirname "$0")/.env"

if [ -f "$ENV_FILE" ]; then
  echo "✅ .env already exists. Delete it and re-run to reconfigure."
  exit 0
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Fatura AI — Dev Environment Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This runs once. Credentials saved to .env (never committed to git)."
echo ""

read -p "Dev Server IP: " DEV_SERVER_IP
read -p "SSH Username (e.g. frappe): " DEV_SERVER_SSH_USER
read -p "SSH Key Path (e.g. ~/.ssh/id_rsa, or press Enter for password auth): " DEV_SERVER_SSH_KEY_PATH
read -p "ERPNext Site Name (e.g. dev.botsolutions.tech): " DEV_SITE_NAME
read -p "ERPNext API Key: " ERPNEXT_API_KEY
read -p "ERPNext API Secret: " ERPNEXT_API_SECRET

cat > "$ENV_FILE" <<EOF
# Fatura AI — Dev Environment
# Generated by setup.sh — DO NOT COMMIT THIS FILE

DEV_SERVER_IP=$DEV_SERVER_IP
DEV_SERVER_SSH_USER=$DEV_SERVER_SSH_USER
DEV_SERVER_SSH_KEY_PATH=$DEV_SERVER_SSH_KEY_PATH
DEV_SITE_NAME=$DEV_SITE_NAME
ERPNEXT_API_KEY=$ERPNEXT_API_KEY
ERPNEXT_API_SECRET=$ERPNEXT_API_SECRET
EOF

echo ""
echo "✅ .env saved successfully."
echo ""
echo "Test your connection:"
if [ -n "$DEV_SERVER_SSH_KEY_PATH" ]; then
  echo "  ssh -i $DEV_SERVER_SSH_KEY_PATH $DEV_SERVER_SSH_USER@$DEV_SERVER_IP"
else
  echo "  ssh $DEV_SERVER_SSH_USER@$DEV_SERVER_IP"
fi
echo ""
echo "Ready. Open Claude Code in this folder and start building."
